### PR TITLE
update point #8 on README for Windows users

### PR DESCRIPTION
**Pull request by DevipriyaSarkar**
update the README for Windows users

### CODE REVIEW

**Comment by raj454raj** [comment]
Hey @DevipriyaSarkar , I don't see a need for this if it is the same for Windows command prompt as in UNIX.

**Comment by DevipriyaSarkar** [comment]
On Windows command prompt, we need to mention the .py part, that is, web2py.py instead of web2py (as in UNIX).
Otherwise it shows
`python: can't open file 'web2py': [Errno 2] No such file or directory`

The .py part is what I meant to point out.

**Comment by raj454raj** [comment]
Oh I see! That's a typo change it to web2py.py, in UNIX also it is supposed to be web2py.py. So no need for a separate Windows part now.

**Comment by DevipriyaSarkar** [comment]
@raj454raj updated :)

**Pull request merged**
