### PR TITLE
Solved Issue #150

### PR DESCRIPTION
**Pull request by vedantrathore**
Added popup method for google calendar api before 30 minutes of the start of the competition

### CODE REVIEW

**Comment by raj454raj** [comment]
Have you tried this ? Because I am not getting any desktop notifications after adding this. Please send a screenshot.

**Comment by vedantrathore** [comment]
Hey! @raj454raj sorry about all the commits mess, I'm kinda learning git and github :sweat_smile:, Please close this PR and I'll send a new one with the bug solved. Also please elaborate on how should I check whether the changes I have made are valid because the reminder is only visible before the competition right?

**Comment by raj454raj** [comment]
> I'm kinda learning git and github 

That's okay.

> Please close this PR and I'll send a new one with the bug solved.

I didn't have any problem with this PR, but after your recent commits, the final PR aims only at solving Issue 147 and not 150 - So I will be closing this PR. Please send a seperate PR for 147 first and then 150.

> Also please elaborate on how should I check whether the changes I have made are valid because the 
> reminder is only visible before the competition right?

Change the remind time to something else instead of 30 minutes ;) ! Also please investigate where is this popup supposed to pop up - We can add it if it is something useful. But for desktop notifications please search a bit on Google. I got these - [1](http://stackoverflow.com/questions/2271156/chrome-desktop-notification-example) and [2](http://blog.teamtreehouse.com/adding-desktop-notifications-to-your-web-applications).

**Comment by vedantrathore** [comment]
For chrome notifications, don't we need to store the user's reminders in the database and then 30 mins before the competition starts show the desktop notification using JS?

If we are using popups by google calendar api, the reminder will automatically show as a popup in google calendar before the competition

**Comment by raj454raj** [comment]
> For chrome notifications, don't we need to store the user's reminders in the database and then 30 mins > before the competition starts show the desktop notification using JS?

I am not sure about that. You will have read up about it.

> If we are using popups by google calendar api, the reminder will automatically show as a popup in 
> google calendar before the competition

If it indeed creates a desktop notification I would be fine with that too. It didn't work for me on localhost. If it works for you, please send a screenshot.
PS: I am not exactly sure where is the popup generated.

**Pull request closed without merging**
