### PR TITLE
#148: profilepage.gif, update with new color rich GIF

### PR DESCRIPTION
**Pull request by rahul-kumi**
Inclusion of the new pie chart into the GIF being displayed on the frontpage.

### CODE REVIEW

**Comment by raj454raj** [comment]
@rahul-kumi : I don't know if this was intentional - but please don't blur the accuracy.

**Comment by raj454raj** [comment]
Thanks @rahul-kumi :+1:

**Comment by rahul-kumi** [comment]
I will correct it in my next PR.

**Comment by rahul-kumi** [comment]
don't close the issue!!

**Comment by raj454raj** [comment]
O oh! I will have to revert this - 
* Blurring the accepted accuracy
* Calendar not showing completely (not your fault but...)
Use this one and send a new PR.
screenshot from 2016-10-13 23 21 56

**Comment by rahul-kumi** [comment]
@raj454raj, was the resolution a problem?

**Comment by raj454raj** [comment]
Umm, yeah the screen size. Works fine with 15 inch screens. Waiting for the next PR.

**Pull request merged**
